
# --- Main Colors ---
background              #141318
foreground              #e6e1e9
cursor                  #e6e1e9
cursor_text_color       #141318

selection_background    #484458
selection_foreground    #e6dff9

url_color               #edb8cb

# --- ANSI Colors ---
color0                  #141318
color1                  #ffb4ab
color2                  #edb8cb
color3                  #cac3dc
color4                  #cbbeff
color5                  #edb8cb
color6                  #cac3dc
color7                  #e6e1e9

color8                  #48454e
color9                  #93000a
color10                 #623b4b
color11                 #484458
color12                 #493f77
color13                 #484458
color14                 #623b4b
color15                 #c9c4d0

# --- Starship Prompt Bubbles ---
color255                #493f77
color254                #cbbeff
color253                #484458
color252                #cac3dc
color251                #623b4b
color250                #edb8cb
color249                #93000a
color248                #ffb4ab

color232                #e6deff
color233                #32285e
color234                #e6dff9
color235                #322e41
color236                #ffd9e5
color237                #492535
color238                #ffdad6
color239                #690005
color240                #e6deff

# Matched with unthemed light/dark
color243                #cbbeff
color244                #ffb4ab
color245                #48454e

# --- UI Elements ---
active_tab_foreground   #32285e
active_tab_background   #cbbeff
inactive_tab_foreground #e6deff
inactive_tab_background #493f77

active_border_color     #cbbeff
inactive_border_color   #938f99

# --- Marks ---
mark1_foreground        #1d1148
mark1_background        #e6deff
mark2_foreground        #1c192b
mark2_background        #e6dff9
mark3_foreground        #30111f
mark3_background        #ffd9e5
