
# --- Main Colors ---
background              #151218
foreground              #e8e0e8
cursor                  #e8e0e8
cursor_text_color       #151218

selection_background    #4d4357
selection_foreground    #ecddf6

url_color               #f2b7bf

# --- ANSI Colors ---
color0                  #151218
color1                  #ffb4ab
color2                  #f2b7bf
color3                  #d0c1da
color4                  #d9bafa
color5                  #f2b7bf
color6                  #d0c1da
color7                  #e8e0e8

color8                  #4a454e
color9                  #93000a
color10                 #653b42
color11                 #4d4357
color12                 #543b71
color13                 #4d4357
color14                 #653b42
color15                 #ccc4cf

# --- Starship Prompt Bubbles ---
color255                #543b71
color254                #d9bafa
color253                #4d4357
color252                #d0c1da
color251                #653b42
color250                #f2b7bf
color249                #93000a
color248                #ffb4ab

color232                #efdbff
color233                #3d2459
color234                #ecddf6
color235                #362d40
color236                #ffd9de
color237                #4b252c
color238                #ffdad6
color239                #690005
color240                #efdbff

# Matched with unthemed light/dark
color243                #d9bafa
color244                #ffb4ab
color245                #4a454e

# --- UI Elements ---
active_tab_foreground   #3d2459
active_tab_background   #d9bafa
inactive_tab_foreground #efdbff
inactive_tab_background #543b71

active_border_color     #d9bafa
inactive_border_color   #958e98

# --- Marks ---
mark1_foreground        #270d43
mark1_background        #efdbff
mark2_foreground        #20182a
mark2_background        #ecddf6
mark3_foreground        #321017
mark3_background        #ffd9de
