map ctrl+shift+e no_op
cursor_trail 100
cursor_trail_decay 0.1 0.5
 
 font_family      FiraCode Nerd Font
 fallback_family  Noto Sans Symbols
 fallback_family  Noto Sans Emoji
 bold_font        auto
 italic_font      auto
 bold_italic_font auto
 font_size 10.0
 cursor_blink_interval -1 ease-in-out
 enable_audio_bell no

draw_minimal_borders yes

background_opacity 0.7

include current-theme.conf
