#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

## [Completion]
## Completion scripts setup. Remove the following line to uninstall
[ -f ~/.dart-cli-completion/bash-config.bash ] && . ~/.dart-cli-completion/bash-config.bash || true
## [/Completion]

export PATH="$PATH:$HOME/resources/scripts/"
