# ~/.bashrc
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

source /usr/share/fzf/key-bindings.bash
source /usr/share/fzf/completion.bash

export ANDROID_SDK_ROOT="$HOME/Android/Sdk"
export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/tools/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
export PATH="$PATH:$HOME/clons/flutter/bin"
export PATH="$HOME/.local/bin:$PATH"
export EDITOR='nvim'


alias get_idf='. $HOME/clons/esp-idf/export.sh; alias idf="idf.py";alias build="time idf.py build"; alias fullclean="idf.py fullclean"'


alias log="git log --all --decorate --oneline --graph"
alias steamopen='xdg-open steam://rungameid/'
alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias cls='clear; fastfetch'
alias please='sudo'
alias pls='sudo'
alias ln='ln -s'
alias :q='exit'

scd(){
    [[ -n "$1" ]] && realpath "$1" > /tmp/scdf
    cd "$(cat /tmp/scdf)"
}

CHARS="󰮯󰊠󱙝󰍳󰛡󰞶󰄛󰩃󰧻󰡚󰣎󰭟󱡂󰊴"

random_char() {
    echo -n "${CHARS:RANDOM % ${#CHARS}:1}"
}

setcolor() {
    # Restablecer colores si no hay argumentos
    if [ -z "$1" ]; then
        echo -n "$(tput sgr0)"
        return 0
    fi
    # Validar que los argumentos sean números
    if ! [[ "$1" =~ ^[0-9]+$ ]]; then
        echo "Error: El primer argumento debe ser un número (color de texto)." >&2
        return -1
    fi

    echo -n "$(tput setaf "$1")"

    if [ -n "$2" ]; then
        if ! [[ "$2" =~ ^[0-9]+$ ]]; then
            echo "Error: El segundo argumento debe ser un número (color de fondo)." >&2
            return -1
        fi
        echo -n "$(tput setab "$2")"
    fi
}


build_prompt() {
    local on_git_repo="$(git rev-parse --is-inside-work-tree 2> /dev/null)"
    local git_branch
    [[ "$on_git_repo" == "true" ]] &&
        git_branch=$(git rev-parse --abbrev-ref HEAD 2> /dev/null)

    local prompt=""
    prompt+="\[$(setcolor 255)\]\[$(setcolor 0)\] \[$(setcolor 4 0)\]   "

    if [[ "$on_git_repo" == "true" ]]; then
        prompt+="\[$(setcolor 0 202)\]"
        prompt+="\[$(setcolor 0 202)\] ${git_branch} "
        prompt+="\[$(setcolor 202 4)\]"
    else
        prompt+="\[$(setcolor 0 4)\]"
    fi

    prompt+="\[$(setcolor 0 4)\] $(random_char)  \\W \[$(setcolor)\]\[$(setcolor 4)\] \[$(setcolor)\]"

    PS1="${prompt}"
}

PROMPT_COMMAND=build_prompt

fastfetch
